import { downloadBlob } from "../fastq/exportFastq.js";

export function save(text, fileName) {
  downloadBlob(new Blob([text], { type: "text/plain" }), fileName);
}

/** NEXUS wrapper around a Newick string (imports into MEGA/FigTree/iTOL). */
export function buildNexusTrees(newick) {
  return [
    "#NEXUS",
    "[Generated by Genome Pipeline Explorer - phylogenetic inference]",
    "",
    "BEGIN TREES;",
    `  TREE tree1 = [&R] ${newick}`,
    "END;",
    "",
  ].join("\n");
}

/** Full square distance matrix as TSV (spreadsheet-ready). */
export function buildMatrixTsv(ids, matrix) {
  const n = ids.length;
  const lines = [["", ...ids].join("\t")];
  for (let i = 0; i < n; i++) {
    const row = [ids[i]];
    for (let j = 0; j < n; j++) row.push(matrix[i * n + j].toFixed(6));
    lines.push(row.join("\t"));
  }
  return lines.join("\n") + "\n";
}
